### ISSUE TITLE
Adding code in c++

### ISSUE THREAD

**Issue by AmanRaj1608** [fuzious/NoMoss#3]
Assign me to add support in C++

 I will try to add these features
- [x] Add support in cpp
- [x] Initialise code in python

**Comment by fuzious** [comment]
Language kon si use krega? I hope java

**Comment by fuzious** [comment]
I hope you will use java ??

**Comment by AmanRaj1608** [comment]
Yes will try to use java
If not I will make different branch and try to keep things in C++
Will report in few days
